### ISSUE TITLE
Fetch user NFTs endpoint

### ISSUE THREAD

**Issue by Robinnnnn** [gallery-so/go-gallery#28]
[GET] /gallery/:id
or
[GET] /users/collections

not sure which one yet

should return an array of collections in the order the user has stored, with each collection containing a title, a description, and an array of NFTs in that collection

we should consider having separate endpoints for authenticated vs. public users to decide whether to return hidden NFTs

**Comment by kaitoo1** [comment]
I like the idea of having separate endpoints for retrieving a public gallery vs retrieving your gallery
