### ISSUE TITLE
cannot use generic type deque.Deque[T any] without instantiation

### ISSUE THREAD

**Issue by chriship** [gallery-so/go-gallery#472]
I seem to be running into the following error when running the build command

```
../go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:50:15: cannot use generic type deque.Deque[T any] without instantiation
```

Referenced here: https://github.com/gammazero/workerpool/issues/63

Any ideas?

**Comment by jarrel-b** [comment]
Hey @chriship sorry just saw this! This seems like something with generics on go1.18, the backend currently uses go1.16.
