### ISSUE TITLE
Auth flow

### ISSUE THREAD

**Issue by Robinnnnn** [gallery-so/go-gallery#5]
Figure out auth handshake

https://www.toptal.com/ethereum/one-click-login-flows-a-metamask-tutorial

By the end of the flow, the user should have a JWT that they used to send requests (either in header or cookies)

**Comment by kaitoo1** [comment]
**metamask**
wallet address: "0x4e6Dde64f6cd29294282000214Fe586b9112739B"
nonce: "testNonceValue"
signature: "0xc5902a1a3102cb9e89e58def4fc2c16d324cc2c668c3b19fca126721a7f85b2a4201d7d573ce52c92e03f93aa95e12da1efd668d9461dc1a2c4cb98cff06a7781c"

**wallet connect**
wallet address: "0x4e6Dde64f6cd29294282000214Fe586b9112739B"
nonce: "testNonceValue"
signature: "0xdb84030e15aff945d28d069fc1eb29b2f069a39e224dab2dd07fc5cec13c4fcf3fb726fc1bc5b796404abd0a91b3ff185c78a55492b33d8e1386907d4eef603b1c"


**wallet link**
wallet address: "0x4e6Dde64f6cd29294282000214Fe586b9112739B"
nonce: "testNonceValue"
signature: "0x44a9326081fa0fde15d1a07a975bde947b5230312857c6c4c0a21f077a87e10f34e4d7f907debb5f67881f1bae893e58ec573890dd49eace61a5a65dde940b5f1b"
