### ISSUE TITLE
"Go get" fails due to willf/bitset 

### ISSUE THREAD

**Issue by Geapefurit** [gallery-so/go-gallery#608]
When I run "go get -u -d ./...",the following error occus.

go: github.com/willf/bitset@v1.3.3: parsing go.mod:
        module declares its path as: github.com/bits-and-blooms/bitset
                but was required as: github.com/willf/bitset

I have noticed the same problem with other project,link: https://github.com/blugelabs/bluge/issues/64

**Comment by jarrel-b** [comment]
Good catch! As a workaround you can run `go get -u=patch -d ./...` so that only the patched version is installed
