### ISSUE TITLE
"make g-docker" fail

### ISSUE THREAD

**Issue by Geapefurit** [gallery-so/go-gallery#609]
The following error appear after runing **"make g-docker"** command.

**docker build -t bcgallery/gallery-postgres:circle -f docker/postgres/circle/DOCKERFILE .**
Sending build context to Docker daemon  3.751MB
Step 1/5 : FROM circleci/postgres
 ---> 75c1bebe6967
Step 2/5 : ENV POSTGRES_HOST_AUTH_METHOD trust
 ---> Using cache
 ---> 9e9ac65f7acb
Step 3/5 : ENV POSTGRES_USER postgres
 ---> Using cache
 ---> 290a35194e99
Step 4/5 : ENV POSTGRES_DB postgres
 ---> Using cache
 ---> abe5df98a77f
**Step 5/5 : COPY db/migrations/*up.sql /docker-entrypoint-initdb.d/**
COPY failed: no source files were specified
make: *** [Makefile:43: g-docker] Error 1

**Comment by Geapefurit** [comment]
The error just appears only in linux.

**Comment by jarrel-b** [comment]
Thanks for reporting! This isn't needed to run the project so removing it from the README.
